export default  {
    '1. Problems':[
        "Pervaya, veri nice stranitsa. Nichego podozritelnogo, prosto tykai paltsami po knopkam)))"
    ],
    '1.1. Formulation':[
        "Morbi vel aliquet est. Morbi pretium lorem nec libero viverra, non viverra diam molestie. Nullam gravida dolor scelerisque sapien mollis, vel maximus dui pellentesque. Sed rutrum, purus ut posuere consectetur, dui purus imperdiet velit, nec sodales massa lectus eget metus. Morbi iaculis quam diam, ut laoreet massa dictum nec. Etiam ultrices dui diam, et venenatis erat posuere ut. Nam magna nibh, fermentum a sapien id, eleifend laoreet est. Cras interdum libero non condimentum mollis. Suspendisse bibendum orci tristique nunc ornare, vitae finibus sem interdum. Etiam neque urna, tempus sit amet orci vel, laoreet rutrum justo. In efficitur mi lorem. Phasellus dictum enim sit amet rutrum laoreet. Nam ac iaculis sapien. Maecenas dictum mattis ipsum at semper. Donec semper vehicula magna, vitae sollicitudin est tempus sit amet. Morbi sodales, mauris sit amet condimentum malesuada, massa est commodo metus, eget pellentesque sem lacus ornare magna."
    ],
    '1.2. Limitations':[
        "Mauris faucibus tristique dapibus. Nullam erat nisi, consectetur id dui sit amet, consectetur interdum nisl. Integer lectus enim, gravida ac ultrices id, aliquet in nulla. Cras vulputate viverra urna faucibus tristique. Pellentesque quis fringilla nibh. Integer nec feugiat risus, ut dictum urna. Aenean a rhoncus ex, vel tempor sapien. Sed in diam egestas, auctor urna posuere, tristique libero. Etiam orci odio, ullamcorper a interdum nec, dictum vel lacus. Curabitur dignissim metus mattis nunc efficitur, posuere ultricies neque tincidunt."
    ],
    '1.3. Possible Solutions':[
        "Nunc molestie velit ullamcorper malesuada volutpat. Vestibulum eu dolor risus. Pellentesque id nisi in ipsum pellentesque gravida sit amet vitae enim. Vivamus pretium in elit quis condimentum. In feugiat, felis in euismod tincidunt, leo arcu euismod felis, quis porta eros magna quis neque. Sed semper faucibus massa non commodo. Sed dictum tortor id mi pellentesque bibendum. Proin fringilla purus libero, a posuere diam commodo a. Aliquam eu finibus mi. Cras eget urna sed lectus semper accumsan. Vivamus lacus lectus, porttitor non auctor sed, tristique non elit. Aliquam sagittis elit magna, quis congue ante malesuada at. In pharetra lectus nec lectus ullamcorper imperdiet."
    ],
    '2. Recursion':[
        "Ut euismod vulputate felis. Proin ultricies accumsan consequat. Sed imperdiet, leo eu congue sagittis, sapien velit posuere arcu, nec pharetra arcu elit non sapien. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam accumsan in nulla id posuere. Quisque mattis cursus consectetur. Proin rhoncus euismod ipsum, sit amet consequat sem pharetra eu. Cras convallis tempor erat nec egestas. Donec malesuada facilisis ultricies. Pellentesque vehicula hendrerit aliquam. Nullam eu metus id sapien auctor porttitor. Aenean suscipit mattis aliquet. Aenean sollicitudin arcu ante, a suscipit felis ornare in."
    ],
    '2.1. Explanation':[
        "Nunc egestas sodales lectus non mollis. Integer sed orci gravida, cursus metus id, vestibulum diam. Mauris consectetur tempor orci id facilisis. Phasellus sollicitudin, est quis fermentum lobortis, augue lorem viverra nulla, ac aliquet leo ligula sit amet sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut congue condimentum quam, eget auctor lorem iaculis pharetra. Morbi vitae nulla congue, laoreet nunc sed, faucibus quam. Mauris laoreet bibendum lorem, at laoreet orci porttitor id. Aenean vehicula vulputate massa, tristique congue massa maximus placerat. Duis aliquam nunc erat, nec placerat ex malesuada vel."
    ],
    '2.2. Examples':[
        "Sed fringilla faucibus semper. Aliquam posuere fringilla magna ut tristique. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris pellentesque elit non augue eleifend tincidunt. Vestibulum suscipit felis augue. Aliquam lorem elit, tempus ac ultricies sit amet, cursus sed nisi. Pellentesque et tellus dui. Aenean egestas risus volutpat est placerat viverra."
    ],
    '2.3. Limitations':[
        "Ut lectus mi, vestibulum pharetra libero eu, finibus tempus neque. In hac habitasse platea dictumst. Duis neque diam, sollicitudin vitae euismod id, lobortis nec eros. Quisque vitae elit eget nisi scelerisque condimentum. Ut enim ipsum, suscipit non egestas ac, pellentesque ut massa. Phasellus tristique turpis sed sapien laoreet luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi at quam ut velit lobortis suscipit. Ut congue et dui sit amet consectetur. Quisque rutrum dapibus efficitur. Nullam ac massa sit amet sem tristique imperdiet. Suspendisse luctus auctor elementum."
    ],
    '3. Dynamic Programming':[
        "Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur vestibulum a augue volutpat sollicitudin. Vestibulum ac lacinia magna, eget condimentum arcu. Quisque lorem massa, fermentum vel tincidunt vitae, consequat vel ante. Etiam sagittis auctor felis, sit amet hendrerit nisl feugiat porta. Mauris elementum consequat ipsum, et fermentum elit. Aliquam quis tortor ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin at ante feugiat, blandit nulla non, pulvinar sapien. Donec viverra, eros quis accumsan rutrum, felis erat pharetra orci, at volutpat nunc felis eget lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eget posuere arcu."
    ],
    '3.1. Explanation':[
        "Donec ut pulvinar velit. Pellentesque varius tellus et sem pharetra, at mollis turpis ullamcorper. Nulla vehicula ac odio nec aliquam. Ut nec dolor vel augue consequat ultrices mattis vitae lectus. Phasellus elementum leo lorem, vitae efficitur elit dignissim tempus. Praesent sit amet faucibus leo. Mauris maximus arcu dapibus faucibus scelerisque."
    ],
    '3.2. Common uses and examples':[
        "Donec nec nisi sed est rutrum rutrum eget et lorem. Suspendisse rutrum metus tellus, lobortis pharetra est malesuada eu. Etiam ultrices orci in metus pretium consectetur. Cras vel eros auctor, scelerisque odio vel, placerat purus. Donec interdum pretium lorem, elementum ornare quam. Ut egestas magna at mauris placerat efficitur. Aenean nec lectus non tellus blandit eleifend. Fusce in nibh interdum, lacinia massa at, rhoncus arcu. Etiam et massa vel nibh tristique vehicula. Aenean accumsan consectetur elit, vel varius nibh commodo at. Aenean vitae velit quis purus dictum hendrerit."
    ],
    '3.3. Analysis':[
        "Існує багато варіацій уривків з Lorem Ipsum, але більшість з них зазнала певних змін на кшталт жартівливих вставок або змішування слів, які навіть не виглядають правдоподібно. Якщо ви збираєтесь використовувати Lorem Ipsum, ви маєте упевнитись в тому, що всередині тексту не приховано нічого, що могло б викликати у читача конфуз. Більшість відомих генераторів Lorem Ipsum в Мережі генерують текст шляхом повторення наперед заданих послідовностей Lorem Ipsum. Принципова відмінність цього генератора робить його першим справжнім генератором Lorem Ipsum. Він використовує словник з більш як 200 слів латини та цілий набір моделей речень - це дозволяє генерувати Lorem Ipsum, який виглядає осмислено. Таким чином, згенерований Lorem Ipsum не міститиме повторів, жартів, нехарактерних для латини слів і т.ін."
    ]
}
